kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: es-scc-admin
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
defaultAddCapabilities: 
- SYS_CHROOT
users:
- my-admin-user
groups:
- my-admin-group
